networks:
  public_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.0.0/24
      driver: default
services:
  haproxy:
    build:
      context: /Users/voosierra/Dev/code/voo-haproxy/services/haproxy
    environment:
      APACHE_1_IP: 192.168.0.11
      APACHE_EXPOSED_PORT: '80'
    expose:
    - 80
    networks:
      public_net:
        ipv4_address: 192.168.0.33
    ports:
    - 80:80/tcp
  web-picam:
    build:
      context: /Users/voosierra/Dev/code/voo-haproxy/services/web-picam
    container_name: apache-web-picam
    expose:
    - '80'
    networks:
      public_net:
        ipv4_address: 192.168.0.11
version: '2.0'
