version: '2.0'
services:
  haproxy:
    build:
      context: /Users/voosierra/Dev/code/voo-haproxy/haproxy
    depends_on:
      - frontend
    environment:
      APACHE_1_IP: 192.168.43.76
      APACHE_EXPOSED_PORT: '80'
    expose:
    - 80
    networks:
      public_net:
        ipv4_address: 192.168.43.76
    ports:
    - 80:80/tcp

  web-picam:
    build:
      context: /Users/voosierra/Dev/code/voo-haproxy/web-picam
    container_name: voohaproxy_picam
    expose:
    - '80'
    networks:
      public_net:
        ipv4_address: 192.168.43.76
