version: '2'
services:
  proxy:
    build:
      context: ./haproxy
    depends_on:
      - frontend
#      - data
    expose:
      - '80'
    ports:
      - '80:80'
  frontend:
    build:
      context: ./web-picam
    devices:
      - "/dev/vchiq"
    container_name: voohaproxy_frontend
    expose:
      - '80'
#  data:
#    build:
#      context: ./data
#    container_name: voohaproxy_data
#    expose:
#      - "8080"
