version: '2'
services:
  haproxy:
    build:
      context: ./haproxy
    depends_on:
      - web-picam
    environment:
      APACHE_EXPOSED_PORT: '80'
    expose:
    - 80
    ports:
    - '80:80'
  web-picam:
    build:
      context: ./web-picam
    container_name: voohaproxy_picam
    expose:
    - '80'
